### ISSUE TITLE
Not loading lang

### ISSUE THREAD

**Issue by wmdhosting** [spicywebau/craft-tinymce#5]
### Bug Description

Upgraded to 4.3  

But still getting this error not loading  lang.. 

All work ok. but TinyMCE take 2-3 second smore to load than other editor.. 
![Snag_10aa64b7](https://user-images.githubusercontent.com/76176291/198003388-a25858e5-d22f-4bba-999c-af421b217a0c.png)

### Steps to reproduce

just open any entry..

### TinyMCE Field version

1.1.1

### Craft CMS version

4.3

**Comment by ttempleton** [comment]
The [official language packages](https://www.tiny.cloud/get-tiny/language-packages/) for TinyMCE aren't included with the plugin, as I'm unsure if the licensing allows us to redistribute them. Instead, the plugin supports adding translations for the editor in the normal Craft way. It'd be good to at least allow a way for users to add the translation packages they'd like to use, though, and I'll look into that soon.

**Comment by wmdhosting** [comment]
strange . as everything is shown in english anyway :)

Regarding licencing. how much they ask.    for full licence.. 
perhps we can do some crowdfunding or something :)

**Comment by ttempleton** [comment]
Disregard the language packs for now - it turned out there was a bug that would have caused the 404 errors to occur anyway, regardless of whether we had a way for users to load language packs. So that's fixed now in 1.2.0.

It'd still be good to allow language packs to be loaded, somehow - maybe have them loaded from `config/tinymce/languages` or something like that - but for now, all translations set the usual Craft way in `translations/<language>/tinymce.php` should work.

**Comment by wmdhosting** [comment]
Great :) thx..
